# I. NumPy.

**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

0. Імпортувати numpy загальноприйнятим способом.

In [2]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [3]:


grades_array = np.array([3, 4, 5])
print(grades_array)



[3 4 5]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [4]:

prices_shop = np.array([
    [12.5, 40.0, 25.3, 100.0],
    [13.0, 39.5, 26.0, 98.5],
    [12.8, 41.0, 25.0, 99.0]])
print(prices_shop)

[[ 12.5  40.   25.3 100. ]
 [ 13.   39.5  26.   98.5]
 [ 12.8  41.   25.   99. ]]


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [5]:
print(grades_array.dtype)
print(prices_shop.dtype)


int64
float64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [6]:

grades = np.array([3, 4, 5])
prices = np.array([[12.5, 40.0, 25.3, 100.0], [13.0, 39.5, 26.0, 98.5], [12.8, 41.0, 25.0, 99.0]])
print(grades.shape, prices.shape)


(3,) (3, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [7]:
sales = np.linspace(0, 1000.50, 7)
print(sales)


[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [8]:

arr_1 = np.array([1, 2, 3, 4])
arr_2 = np.array([228, 229, 230, 231])
vertical_stack = np.vstack((arr_1, arr_2))
horizontal_stack = np.hstack((arr_1, arr_2))
print(vertical_stack)
print(horizontal_stack)

[[  1   2   3   4]
 [228 229 230 231]]
[  1   2   3   4 228 229 230 231]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [28]:

def reshape_array(arr):
    """
    Переміщує заданий масив методом reshape.

    Параметри:
    arr (numpy.ndarray): Вхідний масив для транспонування.

    Повертається:
    numpy.ndarray: Транспонований масив.
    """
    return arr.reshape(arr.shape[1], arr.shape[0])

array1 = np.array([[7, 8, 9], [17, 18, 19]])
print(reshape_array(array1))

array2 = np.array([[2, 4, 6, 8], [10, 12, 14, 16]])
print(reshape_array(array2))




[[ 7  8]
 [ 9 17]
 [18 19]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [10]:
arr_1 = np.array([[4, 2], [8, 6]])
arr_2 = np.array([[10, 11], [21, 22]])
#1
addition = arr_1 + arr_2
print(addition)
#2
subtraction = arr_1 - arr_2
print(subtraction)
#3
mult_by_4_1 = arr_1 * 2
mult_by_4_2 = arr_2 * 2
print(mult_by_4_1)
print(mult_by_4_2)
#4
multiplication = arr_1 * arr_2
print(multiplication)
#5
matrix_multiplication = np.dot(arr_1, arr_2)
print(matrix_multiplication)

[[14 13]
 [29 28]]
[[ -6  -9]
 [-13 -16]]
[[ 8  4]
 [16 12]]
[[20 22]
 [42 44]]
[[ 40  22]
 [168 132]]
[[ 82  88]
 [206 220]]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#1)
min = np.min(matrix)
print(min)
#2)
max = np.max(matrix)
print(max)
#3)
sum = np.sum(matrix)
print(sum)
#4)
min_per_row = np.min(matrix, axis=1)
print(min_per_row)
#5)
max_per_collumn = np.max(matrix, axis=0)
print(max_per_collumn)

1
9
45
[1 4 7]
[7 8 9]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [12]:
matrix = np.array([[1, 2, 3, 4], [5, 2, 1, 6], [7, 8, 9, 1]])
unique_elements, counts = np.unique(matrix, return_counts=True)
print(unique_elements, counts)

[1 2 3 4 5 6 7 8 9] [3 2 1 1 1 1 1 1 1]


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [13]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [14]:
patients = {
    "Surname": ["Vynokur", "Shevchenko", "Petrenko"],
    "Name": ["Artur", "Taras", "Den"],
    "Date of Birth": ["10.08.2005", "30.05.1955", "02.05.2010"],
    "Body weight": ["80.0kg", "70.0kg", "50.0kg"],
    "Health insurance coverage": [None, "Yes", "No"] 
}
patients_data_frame = pd.DataFrame(patients)
print(patients_data_frame)

      Surname   Name Date of Birth Body weight Health insurance coverage
0     Vynokur  Artur    10.08.2005      80.0kg                      None
1  Shevchenko  Taras    30.05.1955      70.0kg                       Yes
2    Petrenko    Den    02.05.2010      50.0kg                        No


In [15]:
print(patients_data_frame.dtypes)

Surname                      object
Name                         object
Date of Birth                object
Body weight                  object
Health insurance coverage    object
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [16]:

file_path = r"C:\Users\Artur\OneDrive\Робочий стіл\labs python\lab1\missile_attacks_daily.csv"
missile_data = pd.read_csv(file_path)
print(missile_data.head())


         time_start          time_end           model  \
0  2025-01-25 19:00  2025-01-26 09:00  Shahed-136/131   
1  2025-01-24 19:00  2025-01-25 09:30  Shahed-136/131   
2  2025-01-24 18:30  2025-01-24 19:30       X-59/X-69   
3  2025-01-23 21:00  2025-01-24 09:00  Shahed-136/131   
4  2025-01-22 19:00  2025-01-23 09:30  Shahed-136/131   

                                        launch_place        target carrier  \
0  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
1  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
2                                          Black Sea  Odesa oblast     NaN   
3  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
4  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   

   launched  destroyed  not_reach_goal  cross_border_belarus  back_russia  \
0      72.0         50             9.0                   NaN          NaN   
1      61.0         46            

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [17]:
print(missile_data.head(10))

         time_start          time_end             model  \
0  2025-01-25 19:00  2025-01-26 09:00    Shahed-136/131   
1  2025-01-24 19:00  2025-01-25 09:30    Shahed-136/131   
2  2025-01-24 18:30  2025-01-24 19:30         X-59/X-69   
3  2025-01-23 21:00  2025-01-24 09:00    Shahed-136/131   
4  2025-01-22 19:00  2025-01-23 09:30    Shahed-136/131   
5  2025-01-23 04:00  2025-01-23 04:30  Iskander-M/KN-23   
6  2025-01-21 19:00  2025-01-22 10:00    Shahed-136/131   
7  2025-01-20 20:00  2025-01-21 09:00    Shahed-136/131   
8  2025-01-20 20:00  2025-01-21 09:00        Iskander-M   
9  2025-01-19 19:00  2025-01-20 08:00    Shahed-136/131   

                                        launch_place        target carrier  \
0  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
1  Primorsko-Akhtarsk and Kursk oblast and Bryans...       Ukraine     NaN   
2                                          Black Sea  Odesa oblast     NaN   
3  Primorsko-Akhtarsk and Kursk oblast

14. Отримайте інформацію про форму датафрейму.

In [18]:
print("Dataframe:", missile_data.shape)

Dataframe: (2056, 16)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [19]:
print(missile_data.info()) 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2056 entries, 0 to 2055
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2056 non-null   object 
 1   time_end              2056 non-null   object 
 2   model                 2056 non-null   object 
 3   launch_place          1034 non-null   object 
 4   target                2028 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2053 non-null   float64
 7   destroyed             2056 non-null   int64  
 8   not_reach_goal        164 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           35 non-null     float64
 11  still_attacking       30 non-null     float64
 12  destroyed_details     301 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      object 
 15  source               

16. Отримайте статистику для колонок числового типу.

In [20]:

numeric_stats = missile_data.describe()
print(numeric_stats)


          launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2053.000000  2056.000000      164.000000             32.000000   
mean     10.872382     7.647860       21.231707              2.312500   
std      21.605295    14.506397       19.812804              2.054696   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        4.000000              1.000000   
50%       2.000000     1.000000       16.000000              2.000000   
75%       9.000000     7.000000       30.000000              2.000000   
max     193.000000    99.000000      105.000000             10.000000   

       back_russia  still_attacking  
count    35.000000        30.000000  
mean      2.000000         2.766667  
std       1.137593         2.848876  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         3.750000  
max       5.000000        10.000000  


17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [21]:
unique_counts = missile_data.nunique()
column_with_min_unique = unique_counts.idxmin()
min_unique_count = unique_counts.min()
print(unique_counts)
print(f"\n '{column_with_min_unique}'")
print(f"unique: {min_unique_count}")
print(missile_data[column_with_min_unique].value_counts())

time_start               874
time_end                1025
model                     61
launch_place             136
target                    97
carrier                   58
launched                 117
destroyed                 83
not_reach_goal            56
cross_border_belarus       7
back_russia                5
still_attacking            8
destroyed_details        297
launched_details           4
launch_place_details       4
source                   968
dtype: int64

 'launched_details'
unique: 4
launched_details
{'X-101/X-555': 50, 'Kalibr': 12}                     1
{'X-101/X-555': 55, 'Kalibr': 24, 'Iskander-K': 7}    1
{'X-101/X-555': 57, 'Kalibr': 28}                     1
{'X-101/X-555': 77, 'Kalibr': 28, 'X-59/X-69': 10}    1
Name: count, dtype: int64


In [ ]:
### Аналіз кількості унікальних значень у стовпцях

# 1. Кількість унікальних значень у кожному стовпці:
# unique_counts[i] = кількість унікальних елементів у стовпці i

# 2. Стовпець із найменшою кількістю унікальних значень:
# column_with_min_unique = argmin(unique_counts[i])

# 3. Мінімальна кількість унікальних значень:
# min_unique_count = min(unique_counts[i])

# 4. Частоти значень у стовпці з найменшою кількістю унікальних значень:
# missile_data[i].value_counts() = {значення: кількість появ}


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1.   Я б звернув увагу типи даних. Треба уважно перевіряти чи всі типи даних було визначено правильно.
2.   Також я б звернув увагу на аномальні значення, важливо виявити та виправити аномальні значення негативних чисел, таких як: кількість жертв, шахедів.

...


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [22]:
df = pd.read_csv('missile_attacks_daily.csv')
df['launched'] = pd.to_numeric(df['launched'], errors='coerce').astype('Int64')
print(df['launched'].info())
print(df['launched'].head())

<class 'pandas.core.series.Series'>
RangeIndex: 2056 entries, 0 to 2055
Series name: launched
Non-Null Count  Dtype
--------------  -----
2053 non-null   Int64
dtypes: Int64(1)
memory usage: 18.2 KB
None
0    72
1    61
2     2
3    58
4    92
Name: launched, dtype: Int64


In [ ]:
# df['launched'] = pd.to_numeric(df['launched'], errors='coerce').astype('Int64')
# Тут я перетворюю стовпець 'launched' на числові значення. Потім цей стовпець приводиться до типу Int64.
# (df['launched'].info())
# Виконую виведення метаданих для стовпця 'launched', зокрема кількості ненульових значень та їх типу.

20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [23]:
total_rows = len(df)
threshold = 0.3 * total_rows
df = df.loc[:, df.count() >= threshold]
print(df.columns)

Index(['time_start', 'time_end', 'model', 'launch_place', 'target', 'launched',
       'destroyed', 'source'],
      dtype='object')


In [ ]:
# фільтруються стовпці DataFrame, залишаючи тільки ті, де кількість ненульових значень становить не менше 30% від загальної кількості рядків.

21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [24]:
print(df.columns)
initial_row_count = len(df)

df = df.drop_duplicates()

if 'duration' in df.columns:
    
    df = df[df['duration'] > 0]
else:
    print("duration haven't been found")

df = df.reset_index(drop=True)

deleted_rows = initial_row_count - len(df)

print(f"Number of deleted rows: {deleted_rows}")


Index(['time_start', 'time_end', 'model', 'launch_place', 'target', 'launched',
       'destroyed', 'source'],
      dtype='object')
duration haven't been found
Number of deleted rows: 0


**місце для текстової відповіді**

In [25]:
 #Кількість видалених рядків була перевірена шляхом порівняння кількості рядків у датафреймі до і після очищення, було видалено 0 рядків.

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [26]:
print(df[df.isnull().any(axis=1)])


            time_start          time_end               model launch_place  \
11          2025-01-20        2025-01-20            Orlan-10          NaN   
24          2025-01-15        2025-01-15                ZALA          NaN   
25          2025-01-15        2025-01-15            Supercam          NaN   
26          2025-01-15        2025-01-15            Orlan-10          NaN   
27          2025-01-15        2025-01-15              Lancet          NaN   
...                ...               ...                 ...          ...   
2051  2022-10-01 12:00  2022-10-01 12:00            Orlan-10          NaN   
2052        2022-09-30        2022-09-30            Orlan-10          NaN   
2053  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131          NaN   
2054        2022-09-28        2022-09-28                X-59          NaN   
2055        2022-09-28        2022-09-28  Reconnaissance UAV          NaN   

                                             target  launched  destroyed  \

In [ ]:
# Код виводить всі рядки DataFrame, які містять хоча б одне пропущене значення.
